### ISSUE TITLE
Contrôler le comportement du client Hypothesis avec les IDs

### ISSUE THREAD

**Issue by emchateau** [publicarchi/ledouxWebapp#4]
- insérer un identifiant sur un paragraphe et un autre sur une division (éventuellement fictive)
- tester l’annotation
- requêter l’annotation dans l’API pour voir comment est renseigner l’ancre de l’annotation

**Comment by emchateau** [comment]
cf. https://docs.basex.org/wiki/HTTP_Client_Module
cf. RESTED (addon Firefox)

**Comment by saranadal** [comment]
Un identifiant a été ajouté à une div puis un autre à un paragraphe. 
Une note a été rédigée au niveau de la div et du paragraphe en mode public.
Après requête, il y a bien eu une réponse mais l'identifiant ne semble pas avoir été pris en compte dans le chemin : 
- pour la note sur le paragraphe :  "endContainer": "/main[1]/div[1]/p[1]/span[1]", "startContainer": "/main[1]/div[1]/p[1]" ;
- pour la note sur la div : "endContainer": "/main[1]/div[1]/h1[1]", "startContainer": "/main[1]/div[1]/h1[1]".

**Comment by emchateau** [comment]
Too bad !
Merci d’avoir essayé.
